-- =============================================================================
-- V1: Baseline of the pre-Flyway schema (Phase 7D.0)
--
-- Purpose: allow a brand-new EMPTY database to be built entirely by Flyway while
-- spring.jpa.hibernate.ddl-auto=validate, so production never depends on
-- hand-executed SQL before the application starts.
--
-- On an ALREADY-POPULATED database this file is NOT executed. Flyway records the
-- existing schema as the baseline (spring.flyway.baseline-on-migrate=true with
-- baseline-version=1), so every object below already exists and is left untouched.
-- Nothing is recreated, nothing is dropped.
--
-- Generated from the live schema with:
--   pg_dump --schema-only --no-owner --no-privileges --no-comments
-- so it matches exactly what Hibernate produced under the previous ddl-auto=update.
--
-- staff_profiles is deliberately absent from this file: it is owned by V2.
-- =============================================================================

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    entity_id bigint,
    entity_type character varying(255) NOT NULL,
    new_value text,
    old_value text,
    performed_by bigint NOT NULL
);

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.clarification_entries (
    id bigint NOT NULL,
    thread_id bigint NOT NULL,
    author_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone DEFAULT NULL::timestamp without time zone
);

ALTER TABLE public.clarification_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clarification_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.clarification_threads (
    id bigint NOT NULL,
    message_id bigint NOT NULL,
    requester_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    created_at timestamp(6) without time zone DEFAULT NULL::timestamp without time zone,
    updated_at timestamp(6) without time zone DEFAULT NULL::timestamp without time zone
);

ALTER TABLE public.clarification_threads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clarification_threads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.companies (
    id bigint NOT NULL,
    active boolean NOT NULL,
    company_type character varying(255),
    created_at timestamp(6) without time zone,
    description text,
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    website character varying(500),
    CONSTRAINT companies_company_type_check CHECK (((company_type)::text = ANY ((ARRAY['PRODUCT'::character varying, 'SERVICE'::character varying, 'CORE'::character varying, 'OTHER'::character varying])::text[])))
);

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.company_reviews (
    id bigint NOT NULL,
    comment text,
    created_at timestamp(6) without time zone,
    job_role character varying(100),
    rating integer NOT NULL,
    company_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.company_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.contact_requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message text NOT NULL,
    resolved_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    student_profile_id bigint NOT NULL,
    target_user_id bigint NOT NULL,
    CONSTRAINT contact_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'RESOLVED'::character varying])::text[])))
);

ALTER TABLE public.contact_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.departments (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.drive_applications (
    id bigint NOT NULL,
    applied_at timestamp(6) without time zone,
    eligibility_reason character varying(512),
    eligible boolean,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    drive_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT drive_applications_status_check CHECK (((status)::text = ANY ((ARRAY['APPLIED'::character varying, 'UNDER_REVIEW'::character varying, 'SHORTLISTED'::character varying, 'REJECTED'::character varying, 'WITHDRAWN'::character varying, 'SELECTED'::character varying])::text[])))
);

ALTER TABLE public.drive_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drive_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.eligibility_allowed_departments (
    eligibility_criteria_id bigint CONSTRAINT eligibility_allowed_department_eligibility_criteria_id_not_null NOT NULL,
    department_id bigint NOT NULL
);

CREATE TABLE public.eligibility_criteria (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    max_active_backlogs integer,
    min_cgpa numeric(38,2),
    min_diploma_pct numeric(38,2),
    min_tenth_pct numeric(38,2),
    min_twelfth_pct numeric(38,2),
    updated_at timestamp(6) without time zone,
    placement_drive_id bigint NOT NULL
);

ALTER TABLE public.eligibility_criteria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eligibility_criteria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.forum_posts (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    parent_id bigint,
    updated_at timestamp(6) without time zone,
    drive_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.forum_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.message_reactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    reaction character varying(255) NOT NULL,
    message_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT message_reactions_reaction_check CHECK (((reaction)::text = ANY ((ARRAY['UPVOTE'::character varying, 'DOWNVOTE'::character varying])::text[])))
);

ALTER TABLE public.message_reactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_reactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.message_recipients (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    delivered_at timestamp(6) without time zone,
    read_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    message_id bigint NOT NULL,
    recipient_id bigint NOT NULL
);

ALTER TABLE public.message_recipients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_recipients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.messages (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    message_type character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    sender_id bigint NOT NULL,
    importance character varying(16) DEFAULT 'NORMAL'::character varying NOT NULL,
    CONSTRAINT messages_importance_check CHECK (((importance)::text = ANY ((ARRAY['NORMAL'::character varying, 'HIGH'::character varying])::text[]))),
    CONSTRAINT messages_message_type_check CHECK (((message_type)::text = ANY ((ARRAY['BROADCAST'::character varying, 'DEPARTMENT'::character varying, 'DIRECT'::character varying])::text[])))
);

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    link character varying(512),
    message text,
    read boolean NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(50),
    user_id bigint NOT NULL
);

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.offers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    file_name character varying(255),
    file_url character varying(512),
    package_lpa numeric(38,2),
    remarks text,
    status character varying(255),
    updated_at timestamp(6) without time zone,
    company_id bigint,
    drive_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT offers_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[])))
);

ALTER TABLE public.offers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.offers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pc_department_assignments (
    id bigint NOT NULL,
    active boolean NOT NULL,
    assigned_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    ended_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    assigned_by bigint,
    department_id bigint NOT NULL,
    pc_user_id bigint NOT NULL
);

ALTER TABLE public.pc_department_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pc_department_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.placement_drives (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    drive_date date,
    job_description text,
    job_role character varying(255) NOT NULL,
    location character varying(255),
    package_lpa numeric(38,2),
    registration_deadline date,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    company_id bigint NOT NULL,
    CONSTRAINT placement_drives_status_check CHECK (((status)::text = ANY ((ARRAY['UPCOMING'::character varying, 'REGISTRATION_OPEN'::character varying, 'REGISTRATION_CLOSED'::character varying, 'ONGOING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.placement_drives ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.placement_drives_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.placement_preference_history (
    id bigint NOT NULL,
    interested boolean NOT NULL,
    reason character varying(500),
    recorded_at timestamp(6) without time zone,
    recorded_by bigint,
    student_profile_id bigint NOT NULL
);

ALTER TABLE public.placement_preference_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.placement_preference_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.placement_records (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    package_lpa numeric(38,2),
    placement_date date,
    status character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone,
    company_id bigint NOT NULL,
    placement_drive_id bigint,
    student_profile_id bigint NOT NULL
);

ALTER TABLE public.placement_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.placement_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pr_assignments (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    demoted_at timestamp(6) without time zone,
    promoted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    department_id bigint NOT NULL,
    promoted_by bigint,
    student_profile_id bigint NOT NULL
);

ALTER TABLE public.pr_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pr_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pr_config (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    max_prs integer NOT NULL,
    updated_at timestamp(6) without time zone,
    department_id bigint NOT NULL
);

ALTER TABLE public.pr_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pr_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.prep_modules (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    sort_order integer NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.prep_modules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prep_modules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.prep_questions (
    id bigint NOT NULL,
    active boolean NOT NULL,
    answer_guide text NOT NULL,
    created_at timestamp(6) without time zone,
    difficulty character varying(255) NOT NULL,
    question text NOT NULL,
    sort_order integer NOT NULL,
    updated_at timestamp(6) without time zone,
    topic_id bigint NOT NULL,
    CONSTRAINT prep_questions_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[])))
);

ALTER TABLE public.prep_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prep_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.prep_topics (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(100) NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    estimated_minutes integer,
    sort_order integer NOT NULL,
    study_guide text NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    module_id bigint NOT NULL
);

ALTER TABLE public.prep_topics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prep_topics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.resume_analyses (
    id bigint NOT NULL,
    ats_compatibility integer,
    contact_checks jsonb,
    content_score integer,
    created_at timestamp(6) without time zone,
    detected_sections jsonb,
    detected_skills jsonb,
    file_name character varying(255) NOT NULL,
    file_size bigint,
    formatting_score integer,
    impact_score integer,
    links_score integer,
    overall_readiness integer,
    page_count integer,
    profile_score integer,
    recommendations jsonb,
    student_profile_id bigint NOT NULL,
    warnings jsonb
);

ALTER TABLE public.resume_analyses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_analyses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.resumes (
    id bigint NOT NULL,
    certifications text,
    created_at timestamp(6) without time zone,
    education text,
    experience text,
    file_name character varying(255),
    file_url character varying(512),
    projects text,
    skills text,
    summary text,
    template character varying(50),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);

ALTER TABLE public.resumes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resumes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.service_company_participation (
    id bigint NOT NULL,
    responded_at timestamp(6) without time zone,
    response character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    placement_drive_id bigint NOT NULL,
    student_profile_id bigint NOT NULL,
    CONSTRAINT service_company_participation_response_check CHECK (((response)::text = ANY ((ARRAY['INTERESTED'::character varying, 'NOT_INTERESTED'::character varying, 'PENDING'::character varying])::text[])))
);

ALTER TABLE public.service_company_participation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_company_participation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.skill_tests (
    id bigint NOT NULL,
    active boolean,
    category character varying(50),
    created_at timestamp(6) without time zone,
    description text,
    duration_minutes integer,
    title character varying(255) NOT NULL,
    total_marks integer
);

ALTER TABLE public.skill_tests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skill_tests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.student_academics (
    id bigint NOT NULL,
    active_backlogs integer,
    cgpa numeric(38,2),
    created_at timestamp(6) without time zone,
    diploma_percentage numeric(38,2),
    history_of_backlogs integer,
    tenth_percentage numeric(38,2),
    twelfth_percentage numeric(38,2),
    updated_at timestamp(6) without time zone,
    student_profile_id bigint NOT NULL
);

ALTER TABLE public.student_academics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_academics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.student_access_codes (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code_hash character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    department_code character varying(255),
    email character varying(255),
    expires_at timestamp(6) without time zone,
    name character varying(255),
    register_number character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    used_at timestamp(6) without time zone,
    created_by bigint,
    student_profile_id bigint
);

ALTER TABLE public.student_access_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_access_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.student_interviews (
    id bigint NOT NULL,
    attended boolean,
    created_at timestamp(6) without time zone,
    interview_date date,
    remarks text,
    round_name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    placement_drive_id bigint NOT NULL,
    student_profile_id bigint NOT NULL,
    CONSTRAINT student_interviews_status_check CHECK (((status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'ATTENDED'::character varying, 'PASSED'::character varying, 'REJECTED'::character varying, 'SELECTED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);

ALTER TABLE public.student_interviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_interviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.student_placement_info (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    interviews_attended integer,
    package_lpa numeric(38,2),
    placement_interested boolean,
    placement_status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    placed_company_id bigint,
    student_profile_id bigint NOT NULL,
    CONSTRAINT student_placement_info_placement_status_check CHECK (((placement_status)::text = ANY ((ARRAY['NOT_PLACED'::character varying, 'PLACED'::character varying, 'BLOCKED'::character varying])::text[])))
);

ALTER TABLE public.student_placement_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_placement_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.student_prep_progress (
    id bigint NOT NULL,
    completed boolean NOT NULL,
    confidence character varying(255),
    updated_at timestamp(6) without time zone,
    student_profile_id bigint NOT NULL,
    topic_id bigint NOT NULL,
    CONSTRAINT student_prep_progress_confidence_check CHECK (((confidence)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[])))
);

ALTER TABLE public.student_prep_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_prep_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.student_professionals (
    id bigint NOT NULL,
    certifications text,
    created_at timestamp(6) without time zone,
    github_url character varying(500),
    linkedin_url character varying(500),
    portfolio_url character varying(500),
    projects text,
    resume_url character varying(500),
    skills text,
    updated_at timestamp(6) without time zone,
    student_profile_id bigint NOT NULL
);

ALTER TABLE public.student_professionals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_professionals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.student_profiles (
    id bigint NOT NULL,
    batch character varying(50),
    created_at timestamp(6) without time zone,
    date_of_birth date,
    phone character varying(20),
    register_number character varying(255) NOT NULL,
    section character varying(20),
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);

ALTER TABLE public.student_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.test_attempts (
    id bigint NOT NULL,
    answers_json text,
    attempted_at timestamp(6) without time zone,
    percentage double precision,
    score integer,
    total integer,
    test_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.test_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.test_questions (
    id bigint NOT NULL,
    correct_option character varying(10),
    marks integer,
    options_json text,
    question_text text NOT NULL,
    test_id bigint NOT NULL
);

ALTER TABLE public.test_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    department_id bigint,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['PO'::character varying, 'PC'::character varying, 'PR'::character varying, 'STUDENT'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.clarification_entries
    ADD CONSTRAINT clarification_entries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.clarification_threads
    ADD CONSTRAINT clarification_threads_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.company_reviews
    ADD CONSTRAINT company_reviews_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.contact_requests
    ADD CONSTRAINT contact_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.drive_applications
    ADD CONSTRAINT drive_applications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.eligibility_allowed_departments
    ADD CONSTRAINT eligibility_allowed_departments_pkey PRIMARY KEY (eligibility_criteria_id, department_id);

ALTER TABLE ONLY public.eligibility_criteria
    ADD CONSTRAINT eligibility_criteria_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.forum_posts
    ADD CONSTRAINT forum_posts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.message_reactions
    ADD CONSTRAINT message_reactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.message_recipients
    ADD CONSTRAINT message_recipients_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pc_department_assignments
    ADD CONSTRAINT pc_department_assignments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.placement_drives
    ADD CONSTRAINT placement_drives_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.placement_preference_history
    ADD CONSTRAINT placement_preference_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.placement_records
    ADD CONSTRAINT placement_records_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pr_assignments
    ADD CONSTRAINT pr_assignments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pr_config
    ADD CONSTRAINT pr_config_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.prep_modules
    ADD CONSTRAINT prep_modules_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.prep_questions
    ADD CONSTRAINT prep_questions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.prep_topics
    ADD CONSTRAINT prep_topics_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.resume_analyses
    ADD CONSTRAINT resume_analyses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT resumes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.service_company_participation
    ADD CONSTRAINT service_company_participation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.skill_tests
    ADD CONSTRAINT skill_tests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_academics
    ADD CONSTRAINT student_academics_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_access_codes
    ADD CONSTRAINT student_access_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_interviews
    ADD CONSTRAINT student_interviews_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_placement_info
    ADD CONSTRAINT student_placement_info_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_prep_progress
    ADD CONSTRAINT student_prep_progress_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_professionals
    ADD CONSTRAINT student_professionals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT student_profiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.test_attempts
    ADD CONSTRAINT test_attempts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.test_questions
    ADD CONSTRAINT test_questions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_academics
    ADD CONSTRAINT uk2rnt41sq6yrnbxspw18dfbqwy UNIQUE (student_profile_id);

ALTER TABLE ONLY public.student_placement_info
    ADD CONSTRAINT uk5p1lj2wbuaaqcrpeygskaax0o UNIQUE (student_profile_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.student_access_codes
    ADD CONSTRAINT ukampdcamvijylcvaj651g33pe2 UNIQUE (student_profile_id);

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT ukayvbsmc5akt4p50s68k9jjx9p UNIQUE (register_number);

ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT ukbwy42hdh23n1jypl7y8hna8y7 UNIQUE (user_id);

ALTER TABLE ONLY public.clarification_threads
    ADD CONSTRAINT ukd6e2qeveyk8w6kxgox3dy9h63 UNIQUE (message_id, requester_id);

ALTER TABLE ONLY public.prep_modules
    ADD CONSTRAINT ukepk2ljhj7dob107io0bjybma0 UNIQUE (code);

ALTER TABLE ONLY public.pr_config
    ADD CONSTRAINT ukhjcksnrelokgcn85u6taw1l3o UNIQUE (department_id);

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT ukhlcwb2egnj8mj3e0mouse1lgy UNIQUE (user_id);

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT ukj6cwks7xecs5jov19ro8ge3qk UNIQUE (name);

ALTER TABLE ONLY public.prep_topics
    ADD CONSTRAINT ukk43j4ujpyfucowgmve3kc69dh UNIQUE (code);

ALTER TABLE ONLY public.eligibility_criteria
    ADD CONSTRAINT ukkrnk3ai4eqposdad4lot2s1w9 UNIQUE (placement_drive_id);

ALTER TABLE ONLY public.drive_applications
    ADD CONSTRAINT ukkvpv0573pbkqce4yj7qkxhs15 UNIQUE (user_id, drive_id);

ALTER TABLE ONLY public.student_professionals
    ADD CONSTRAINT ukps5a4gvc74ctjfmn994yr40lw UNIQUE (student_profile_id);

ALTER TABLE ONLY public.message_reactions
    ADD CONSTRAINT ukq21iskriotbxupl6p6wdhltf8 UNIQUE (message_id, user_id);

ALTER TABLE ONLY public.student_prep_progress
    ADD CONSTRAINT uq_student_prep_topic UNIQUE (student_profile_id, topic_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_audit_logs_created ON public.audit_logs USING btree (created_at DESC);

CREATE INDEX idx_audit_logs_performed_by_created ON public.audit_logs USING btree (performed_by, created_at DESC);

CREATE INDEX idx_clarif_entries_thread ON public.clarification_entries USING btree (thread_id);

CREATE INDEX idx_contact_requests_target_created ON public.contact_requests USING btree (target_user_id, created_at DESC);

CREATE INDEX idx_message_recipients_message ON public.message_recipients USING btree (message_id);

CREATE INDEX idx_message_recipients_recipient_created ON public.message_recipients USING btree (recipient_id, created_at DESC);

CREATE INDEX idx_messages_sender_created ON public.messages USING btree (sender_id, created_at DESC);

CREATE INDEX idx_placement_drives_company ON public.placement_drives USING btree (company_id);

CREATE INDEX idx_placement_drives_status_date ON public.placement_drives USING btree (status, drive_date DESC);

CREATE INDEX idx_prep_questions_topic_sort ON public.prep_questions USING btree (topic_id, sort_order);

CREATE INDEX idx_prep_topics_module_sort ON public.prep_topics USING btree (module_id, sort_order);

CREATE INDEX idx_resume_analyses_student_created ON public.resume_analyses USING btree (student_profile_id, created_at);

CREATE UNIQUE INDEX uk_clarif_thread_message_requester ON public.clarification_threads USING btree (message_id, requester_id);

CREATE UNIQUE INDEX uq_sac_register_number ON public.student_access_codes USING btree (register_number);

ALTER TABLE ONLY public.message_reactions
    ADD CONSTRAINT fk1o714y33gam6b6741ci4ho041 FOREIGN KEY (message_id) REFERENCES public.messages(id);

ALTER TABLE ONLY public.clarification_entries
    ADD CONSTRAINT fk1v3yd3ji525jfshu2r98apbho FOREIGN KEY (author_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.message_recipients
    ADD CONSTRAINT fk1v4eg8ytqvjrfbfw63mwpmtf5 FOREIGN KEY (message_id) REFERENCES public.messages(id);

ALTER TABLE ONLY public.student_access_codes
    ADD CONSTRAINT fk306t5tyo2hye9c2bxeebnhpb6 FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT fk32koy3tgqtaujxhfsn0b9pel2 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT fk340nuaivxiy99hslr3sdydfvv FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.drive_applications
    ADD CONSTRAINT fk3f8pss3gterbbqmqeh852h0k7 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.placement_preference_history
    ADD CONSTRAINT fk53cexhhaj55scf2p0pq36qs09 FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.clarification_threads
    ADD CONSTRAINT fk5nn4xaofv3we13r80uctd4my6 FOREIGN KEY (sender_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.forum_posts
    ADD CONSTRAINT fk5x8ptdw4oolxbyoecsyxna5kf FOREIGN KEY (drive_id) REFERENCES public.placement_drives(id);

ALTER TABLE ONLY public.student_access_codes
    ADD CONSTRAINT fk65ycv7r96ia6hphy3ag7i7uy9 FOREIGN KEY (created_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.test_questions
    ADD CONSTRAINT fk66s7pajfnimitxvmiw3u12yjl FOREIGN KEY (test_id) REFERENCES public.skill_tests(id);

ALTER TABLE ONLY public.student_interviews
    ADD CONSTRAINT fk69epjqpi6fp8wb5a1rj9xttfa FOREIGN KEY (placement_drive_id) REFERENCES public.placement_drives(id);

ALTER TABLE ONLY public.test_attempts
    ADD CONSTRAINT fk6q32269iwnavc4q6o46lwyu3u FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.test_attempts
    ADD CONSTRAINT fk6wnrrbqffgj7u2md2hjwh73vi FOREIGN KEY (test_id) REFERENCES public.skill_tests(id);

ALTER TABLE ONLY public.placement_records
    ADD CONSTRAINT fk8s73apvuypdfbrmowo83qxs0l FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.forum_posts
    ADD CONSTRAINT fk9f512v035ct3wtwwx343yxh5u FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fk9yilcimbeupq2lyrqr1nlrjyb FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.student_prep_progress
    ADD CONSTRAINT fkasnagb8l7otgwlm7hm05t9ufc FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.placement_records
    ADD CONSTRAINT fkatlpohedpc9pxqyso255mp2p FOREIGN KEY (company_id) REFERENCES public.companies(id);

ALTER TABLE ONLY public.pr_assignments
    ADD CONSTRAINT fkax1ukmw0pyfuiohtcy95oetx6 FOREIGN KEY (promoted_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.contact_requests
    ADD CONSTRAINT fkc4pbjhpe9obsiupla4x17252f FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.clarification_threads
    ADD CONSTRAINT fkc9y2ngvoyyumxi5wqd65uanof FOREIGN KEY (message_id) REFERENCES public.messages(id);

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fkd43pee8ph6a5juqp52dinhypa FOREIGN KEY (drive_id) REFERENCES public.placement_drives(id);

ALTER TABLE ONLY public.pr_assignments
    ADD CONSTRAINT fkd4v087uxq7t6stara1ca6nwnc FOREIGN KEY (department_id) REFERENCES public.departments(id);

ALTER TABLE ONLY public.contact_requests
    ADD CONSTRAINT fkef75c6n98cgwblx4p6dkcwvgm FOREIGN KEY (target_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.pr_config
    ADD CONSTRAINT fken7eu8nqk6d2crngpsdhd7ow2 FOREIGN KEY (department_id) REFERENCES public.departments(id);

ALTER TABLE ONLY public.pc_department_assignments
    ADD CONSTRAINT fkeo0e2j6noq7e1d91le4nddwvo FOREIGN KEY (pc_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.prep_questions
    ADD CONSTRAINT fkfcpp70ujopweneh2mirxpe0be FOREIGN KEY (topic_id) REFERENCES public.prep_topics(id);

ALTER TABLE ONLY public.student_placement_info
    ADD CONSTRAINT fkfgk1sof44ef2pv6codpsbm7t0 FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.service_company_participation
    ADD CONSTRAINT fkg4wbjt2s07fwx8g53jqrbgmpw FOREIGN KEY (placement_drive_id) REFERENCES public.placement_drives(id);

ALTER TABLE ONLY public.clarification_entries
    ADD CONSTRAINT fkg5hrblcm9j8fv48bekhg4csne FOREIGN KEY (thread_id) REFERENCES public.clarification_threads(id);

ALTER TABLE ONLY public.eligibility_allowed_departments
    ADD CONSTRAINT fkgqyysay256nr80ns4g6f49rdt FOREIGN KEY (eligibility_criteria_id) REFERENCES public.eligibility_criteria(id);

ALTER TABLE ONLY public.student_interviews
    ADD CONSTRAINT fkgvnmk92oixonlufudyobovdpv FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.student_academics
    ADD CONSTRAINT fkhhha7ewxitfhmjvqdp12kcy87 FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.pc_department_assignments
    ADD CONSTRAINT fkieej112b280tsw7ulfpd3l11b FOREIGN KEY (department_id) REFERENCES public.departments(id);

ALTER TABLE ONLY public.placement_drives
    ADD CONSTRAINT fkih6endh3inkdy2ya86k448aem FOREIGN KEY (company_id) REFERENCES public.companies(id);

ALTER TABLE ONLY public.student_professionals
    ADD CONSTRAINT fkikpwv6w18twhxfgmhl7es1h6k FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.student_placement_info
    ADD CONSTRAINT fkj7iqgsfmxb2k1f56oqr7hdgvt FOREIGN KEY (placed_company_id) REFERENCES public.companies(id);

ALTER TABLE ONLY public.company_reviews
    ADD CONSTRAINT fkjlwevafsv6wcpvt0jg5tfs1f0 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.clarification_threads
    ADD CONSTRAINT fkk045ws8wdpyk29wj7uuxelbli FOREIGN KEY (requester_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.company_reviews
    ADD CONSTRAINT fkkpjxpw5kl37cad0twqje6cq63 FOREIGN KEY (company_id) REFERENCES public.companies(id);

ALTER TABLE ONLY public.prep_topics
    ADD CONSTRAINT fkl40vajgjseywx6wfiemx0vkkl FOREIGN KEY (module_id) REFERENCES public.prep_modules(id);

ALTER TABLE ONLY public.service_company_participation
    ADD CONSTRAINT fklcev5c10o98ca5no1k37lyyt FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.drive_applications
    ADD CONSTRAINT fkliof6ah10bahcmhhq8ggdi2sl FOREIGN KEY (drive_id) REFERENCES public.placement_drives(id);

ALTER TABLE ONLY public.placement_records
    ADD CONSTRAINT fklx9oy8nq1cyk9qr1xib9tify2 FOREIGN KEY (placement_drive_id) REFERENCES public.placement_drives(id);

ALTER TABLE ONLY public.eligibility_allowed_departments
    ADD CONSTRAINT fknboi9pogdfcluxl9g01p04pra FOREIGN KEY (department_id) REFERENCES public.departments(id);

ALTER TABLE ONLY public.pc_department_assignments
    ADD CONSTRAINT fko7auikike1vmodi7aa3xgb7hy FOREIGN KEY (assigned_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.pr_assignments
    ADD CONSTRAINT fkof060184m3ra67gm0btuahdvj FOREIGN KEY (student_profile_id) REFERENCES public.student_profiles(id);

ALTER TABLE ONLY public.message_reactions
    ADD CONSTRAINT fkoip2ttlg2py976foointttaew FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fkonjalmr7kf8970g8gu7ymueer FOREIGN KEY (performed_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.message_recipients
    ADD CONSTRAINT fkotvrxaectwcf0ljaywg8lm8bx FOREIGN KEY (recipient_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fkpseep21h5a3wppbeooi10ghk8 FOREIGN KEY (company_id) REFERENCES public.companies(id);

ALTER TABLE ONLY public.placement_preference_history
    ADD CONSTRAINT fkq3ybsbsta84ekp9xmqrqll4is FOREIGN KEY (recorded_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.eligibility_criteria
    ADD CONSTRAINT fkqptejinsjtxp419u9oxtmug82 FOREIGN KEY (placement_drive_id) REFERENCES public.placement_drives(id);

ALTER TABLE ONLY public.student_prep_progress
    ADD CONSTRAINT fkr2u9aiyavylal5oq3v14my4up FOREIGN KEY (topic_id) REFERENCES public.prep_topics(id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fksbg59w8q63i0oo53rlgvlcnjq FOREIGN KEY (department_id) REFERENCES public.departments(id);

