-- =============================================================================
-- V2: staff_profiles - editable professional profile for PC and PO (Phase 7P.5)
--
-- Additive only. Creates one new table; touches no existing table and no data.
-- Schema is identical to the DDL certified in PHASE-7P.5-REPORT.md section 8.
--
-- IF NOT EXISTS is intentional and is NOT a substitute for Flyway history:
--   * Flyway records this migration in flyway_schema_history, so on any given
--     database it executes exactly once and never repeats.
--   * The guard exists only for long-lived development databases that were
--     built by the previous ddl-auto=update strategy and therefore already
--     contain staff_profiles (with real rows). It lets those databases adopt
--     Flyway without dropping or recreating the table, so existing rows
--     survive the introduction of migrations.
--   * It is deliberately NOT implemented as a startup check in application
--     code. All schema change decisions live in this versioned directory.
--
-- No credentials or secrets appear in this file.
-- =============================================================================

CREATE TABLE IF NOT EXISTS staff_profiles (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    phone           VARCHAR(25),
    designation     VARCHAR(120),
    office_location VARCHAR(150),
    bio             VARCHAR(1000),
    linkedin_url    VARCHAR(500),
    expertise       JSONB,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT uq_staff_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_staff_profiles_user FOREIGN KEY (user_id) REFERENCES users (id)
);
