-- =============================================================================
-- V3: Mock Interview sessions (Phase 7N.2B)
--
-- Additive only. Creates two new tables; touches no existing table and no data.
--
-- DESIGN NOTES
--
-- 1. No duplicate question bank.
--    This migration stores NO question text, options, correct answers or
--    explanations. mock_interview_session_questions holds only a foreign key
--    (question_id) to the existing prep_questions row. All question content is
--    read live from the preparation domain, so Mock Interview and Interview
--    Prep can never drift apart and no content is duplicated.
--
--    Consequence (deliberate): historical sessions render the CURRENT text of a
--    question. If a question is later reworded, old sessions show the new
--    wording. Audit-perfect snapshots would require copying the content into
--    this table; that is intentionally deferred until it is actually needed.
--
-- 2. No objective-grading columns.
--    The certified preparation bank is 100% descriptive: prep_questions has no
--    question-type, options or correct-answer column, and all 278 rows carry a
--    free-text answer_guide. There is therefore nothing legitimate to score, so
--    there is no is_correct / awarded_score column here. Grading for descriptive
--    content is left to the student's own self-assessment, which is stored as
--    self_rating below.
--
-- 3. One active session per student is enforced by the database.
--    uq_mock_interview_session_active is a PARTIAL unique index over
--    status = 'IN_PROGRESS', so the "only one unfinished interview" rule cannot
--    be bypassed by concurrent requests. Completed and abandoned history is
--    unaffected.
--
-- 4. No IF NOT EXISTS guard.
--    Unlike V2 (which had to adopt a table created by the old ddl-auto=update
--    strategy), these tables have never existed anywhere. Flyway records this
--    migration in flyway_schema_history, so on any given database it executes
--    exactly once; a guard would only hide a genuine partial-failure.
--
-- No credentials or secrets appear in this file.
-- =============================================================================

CREATE TABLE mock_interview_sessions (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id  BIGINT       NOT NULL,
    interview_type      VARCHAR(30)  NOT NULL,
    difficulty          VARCHAR(20)  NOT NULL,
    question_count      INTEGER      NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    started_at          TIMESTAMP(6) NOT NULL,
    completed_at        TIMESTAMP(6),
    duration_seconds    INTEGER,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_mock_interview_session_student
        FOREIGN KEY (student_profile_id) REFERENCES student_profiles (id) ON DELETE CASCADE,

    CONSTRAINT ck_mock_interview_session_type
        CHECK (interview_type IN ('TECHNICAL', 'HR_BEHAVIORAL', 'MIXED')),
    CONSTRAINT ck_mock_interview_session_difficulty
        CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD', 'MIXED')),
    CONSTRAINT ck_mock_interview_session_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED')),
    CONSTRAINT ck_mock_interview_session_count
        CHECK (question_count > 0),
    CONSTRAINT ck_mock_interview_session_duration
        CHECK (duration_seconds IS NULL OR duration_seconds >= 0)
);

-- History list: "my interviews, newest first" for one student.
CREATE INDEX idx_mock_interview_session_student_created
    ON mock_interview_sessions (student_profile_id, created_at DESC);

-- Resume lookup: "do I have an unfinished interview?".
CREATE INDEX idx_mock_interview_session_student_status
    ON mock_interview_sessions (student_profile_id, status);

-- At most one IN_PROGRESS session per student, enforced in the database.
CREATE UNIQUE INDEX uq_mock_interview_session_active
    ON mock_interview_sessions (student_profile_id)
    WHERE status = 'IN_PROGRESS';

CREATE TABLE mock_interview_session_questions (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      BIGINT       NOT NULL,
    question_id     BIGINT       NOT NULL,
    position        INTEGER      NOT NULL,
    student_answer  TEXT,
    self_rating     VARCHAR(30),
    answered_at     TIMESTAMP(6),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_mock_session_question_session
        FOREIGN KEY (session_id) REFERENCES mock_interview_sessions (id) ON DELETE CASCADE,

    -- NO ACTION (not CASCADE) on purpose: a preparation question that has been
    -- used in an interview must not be hard-deleted, because history would lose
    -- its meaning. Questions are retired with the existing `active` flag instead.
    CONSTRAINT fk_mock_session_question_question
        FOREIGN KEY (question_id) REFERENCES prep_questions (id),

    -- Fixed, gap-free interview order; also the primary read path for a session.
    CONSTRAINT uq_mock_session_question_position UNIQUE (session_id, position),

    -- The same question can never appear twice in one session, so a short
    -- requested count is never padded by repeating questions.
    CONSTRAINT uq_mock_session_question_question UNIQUE (session_id, question_id),

    CONSTRAINT ck_mock_session_question_position CHECK (position > 0),
    CONSTRAINT ck_mock_session_question_rating
        CHECK (self_rating IS NULL
               OR self_rating IN ('NEED_PRACTICE', 'PARTIALLY_CONFIDENT', 'CONFIDENT')),
    -- 5000 characters is the documented descriptive-answer ceiling.
    CONSTRAINT ck_mock_session_question_answer_length
        CHECK (student_answer IS NULL OR length(student_answer) <= 5000)
);
