-- V4: Registration verification codes table for email-based student registration.
-- Stores hashed one-time codes sent to authorized student emails during
-- the self-registration flow. Plaintext codes are never persisted.

CREATE TABLE public.registration_verification_codes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorized_student_id BIGINT NOT NULL,
    email           VARCHAR(255) NOT NULL,
    code_hash       VARCHAR(255) NOT NULL,
    expires_at      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    attempt_count   INTEGER NOT NULL DEFAULT 0,
    verified_at     TIMESTAMP(6) WITHOUT TIME ZONE,
    used_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_rvc_authorized_student
        FOREIGN KEY (authorized_student_id)
        REFERENCES public.student_access_codes(id)
);

CREATE INDEX idx_rvc_authorized_student ON public.registration_verification_codes (authorized_student_id);
CREATE INDEX idx_rvc_email_expires ON public.registration_verification_codes (email, expires_at);
