package com.college.placement.accesscode;

import com.college.placement.accesscode.dto.GenerateAccessCodesResponse;
import com.college.placement.common.exception.BadRequestException;
import com.college.placement.department.DepartmentCodeResolver;
import com.college.placement.student.StudentAccessCode;
import com.college.placement.student.StudentAccessCodeRepository;
import com.college.placement.user.User;
import com.college.placement.user.UserRepository;
import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.CSVWriter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Service
@RequiredArgsConstructor
@Slf4j
public class AccessCodeService {

    private final StudentAccessCodeRepository accessCodeRepository;
    private final DepartmentCodeResolver departmentResolver;
    private final AccessCodeHasher accessCodeHasher;
    private final AccessCodeGenerator accessCodeGenerator;
    private final UserRepository userRepository;

    @Value("${app.authorized-csv-path:data/authorized_users.csv}")
    private String authorizedCsvPath;

    @Value("${app.generated-codes-csv-path:data/generated_access_codes.csv}")
    private String generatedCodesCsvPath;

    @Transactional
    public GenerateAccessCodesResponse generateCodes(Long adminUserId) {
        File csv = new File(authorizedCsvPath);
        if (!csv.exists()) {
            throw new BadRequestException("Authorized CSV not found at " + csv.getAbsolutePath());
        }

        List<AuthorizedStudent> students = parseCsv(csv);

        Set<String> existingRegs = accessCodeRepository.findAll().stream()
                .map(StudentAccessCode::getRegisterNumber)
                .collect(java.util.stream.Collectors.toSet());

        Map<String, Boolean> deptOk = new HashMap<>();
        for (AuthorizedStudent student : students) {
            deptOk.computeIfAbsent(student.departmentCode().trim().toUpperCase(),
                    code -> departmentResolver.resolve(code).isPresent());
        }

        User adminUser = userRepository.findById(adminUserId).orElse(null);
        Set<String> usedCodes = new HashSet<>();
        List<StudentAccessCode> toSave = new ArrayList<>();
        List<String[]> rowsToAppend = new ArrayList<>();
        rowsToAppend.add(new String[]{"Name", "Department", "RegisterNumber", "AccessCode"});

        int created = 0;
        int skipped = 0;

        for (AuthorizedStudent student : students) {
            if (existingRegs.contains(student.registerNumber())) {
                skipped++;
                continue;
            }
            if (!deptOk.getOrDefault(student.departmentCode().trim().toUpperCase(), false)) {
                log.warn("Skipping {} - unknown department code '{}'", student.registerNumber(), student.departmentCode());
                skipped++;
                continue;
            }

            String code = accessCodeGenerator.generateUnique(usedCodes);
            toSave.add(StudentAccessCode.builder()
                    .registerNumber(student.registerNumber())
                    .name(student.name())
                    .departmentCode(student.departmentCode())
                    .codeHash(accessCodeHasher.hash(code))
                    .createdBy(adminUser)
                    .active(true)
                    .build());
            usedCodes.add(code);
            rowsToAppend.add(new String[]{student.name(), student.departmentCode(), student.registerNumber(), code});
            created++;
        }

        if (!toSave.isEmpty()) {
            accessCodeRepository.saveAll(toSave);
        }
        if (created > 0) {
            appendPlaintext(rowsToAppend);
        }

        log.info("Access codes generated by user {}: {} created, {} skipped of {} rows",
                adminUserId, created, skipped, students.size());

        return GenerateAccessCodesResponse.builder()
                .totalCsvRows(students.size())
                .created(created)
                .skipped(skipped)
                .plaintextFile(new File(generatedCodesCsvPath).getAbsolutePath())
                .build();
    }

    private List<AuthorizedStudent> parseCsv(File file) {
        List<AuthorizedStudent> students = new ArrayList<>();
        Set<String> seen = new HashSet<>();
        try (CSVReader reader = new CSVReaderBuilder(new FileReader(file)).withSkipLines(1).build()) {
            String[] line;
            while ((line = reader.readNext()) != null) {
                if (line.length < 3 || isBlank(line[0]) || isBlank(line[1]) || isBlank(line[2])) {
                    continue;
                }
                String name = line[0].trim();
                String dept = line[1].trim();
                String regNo = line[2].trim();
                if (seen.add(regNo)) {
                    students.add(new AuthorizedStudent(name, dept, regNo));
                }
            }
        } catch (Exception e) {
            throw new BadRequestException("Failed to read authorized CSV: " + e.getMessage());
        }
        return students;
    }

    private void appendPlaintext(List<String[]> rows) {
        File file = new File(generatedCodesCsvPath);
        File parent = file.getParentFile();
        if (parent != null && !parent.exists()) {
            parent.mkdirs();
        }
        boolean hasExisting = file.exists() && file.length() > 0;
        try (CSVWriter writer = new CSVWriter(new FileWriter(file, true))) {
            for (String[] row : rows) {
                writer.writeNext(row);
            }
        } catch (Exception e) {
            log.error("Failed to write generated codes file", e);
            throw new BadRequestException("Failed to write generated access codes: " + e.getMessage());
        }
    }

    private boolean isBlank(String s) {
        return s == null || s.trim().isEmpty();
    }
}
